
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--tag', 'gcr.io/$rdev-projeto1/my-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$rdev-projeto1D/my-app']
timeout: '1600s'
images:
- 'gcr.io/$rdev-projeto1/my-app'
